# Generated by Django 5.2.11 on 2026-08-11 10:07

import django.db.models.deletion
import validators.validators_profiles
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.PositiveIntegerField(blank=True, choices=[(1, 'MALE'), (2, 'FEMALE')], default=None, null=True)),
                ('clothing_size', models.PositiveIntegerField(blank=True, choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXl')], default=None, null=True)),
                ('shoe_size', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('birthday', models.DateField(blank=True, null=True, validators=[validators.validators_profiles.profile_birthday_validator])),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[validators.validators_profiles.profile_phone_validator])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
