services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    entrypoint: ""
    command: >
      bash -c "
      python api_shop/manage.py migrate &&
      python api_shop/manage.py loaddata sizes.json colors.json &&
      python api_shop/manage.py load_brands &&
      python api_shop/manage.py load_category &&
      python api_shop/manage.py load_terms &&
      python api_shop/manage.py create_default_superuser &&
      python api_shop/manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/app
      - static_value:/static/
      - media_value:/media/
    ports:
      - "8080:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  static_value:
  media_value:
  db_data:
