# Generated by Django 5.2.11 on 2026-07-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('product_variants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='product_variants.productvariant'),
        ),
    ]
