# Generated by Django 5.2.11 on 2026-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_initial'),
        ('product_variants', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='value',
            new_name='amount',
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['product_variant'], name='discounts_d_product_20af67_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['discount_type'], name='discounts_d_discoun_f47d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['start_at'], name='discounts_d_start_a_ac018f_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['end_at'], name='discounts_d_end_at_2320b6_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active'], name='discounts_d_is_acti_ae32b7_idx'),
        ),
    ]
