# Generated by Django 5.2.11 on 2026-07-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_rename_value_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discount',
            name='discounts_d_product_20af67_idx',
        ),
        migrations.RemoveIndex(
            model_name='discount',
            name='discounts_d_discoun_f47d7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='discount',
            name='discounts_d_is_acti_ae32b7_idx',
        ),
    ]
