# Generated by Django 5.2.11 on 2026-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['sort_order'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.RemoveField(
            model_name='size',
            name='is_active',
        ),
        migrations.AddField(
            model_name='size',
            name='size_type',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], default='clothing', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
