# Generated by Django 5.2.11 on 2026-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_images', '0002_initial'),
        ('product_variants', '0003_alter_productvariant_gender_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product_variant'], name='product_ima_product_e8557c_idx'),
        ),
    ]
