# Generated by Django 5.2.11 on 2026-07-27 19:03

import product_images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_images', '0003_productimage_product_ima_product_e8557c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=product_images.models.product_image_upload_path),
        ),
    ]
