# Generated by Django 5.2.11 on 2026-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_images', '0004_alter_productimage_image'),
        ('product_variants', '0004_remove_productvariant_product_var_product_55988d_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product_variant',), name='unique_main_image_per_product_variant'),
        ),
    ]
