# Generated by Django 5.2.11 on 2026-04-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_created_at_category_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
