# Generated by Django 5.2.11 on 2026-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_remove_category_parent_subcategory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category'], name='categories__categor_0b5d56_idx'),
        ),
    ]
