# Generated by Django 5.2.11 on 2026-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
        ('product_variants', '0002_initial'),
        ('products', '0001_initial'),
        ('sizes', '0002_alter_size_options_remove_size_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='product_var_product_55988d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['size'], name='product_var_size_id_8c94fe_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['color'], name='product_var_color_i_f5f13d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['gender'], name='product_var_gender_fc1c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active'], name='product_var_is_acti_b13d5d_idx'),
        ),
    ]
