# Generated by Django 5.2.11 on 2026-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
        ('product_variants', '0003_alter_productvariant_gender_and_more'),
        ('products', '0001_initial'),
        ('sizes', '0002_alter_size_options_remove_size_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_product_55988d_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_size_id_8c94fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_color_i_f5f13d_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_gender_fc1c2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_is_acti_b13d5d_idx',
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'size'], name='product_var_product_6d188a_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'gender'], name='product_var_product_c12f50_idx'),
        ),
    ]
